sudo: required


language: java

jdk: oraclejdk8

services:
  - docker

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/BaardBouvet-patch-1/after_success.sh)
